version: "3"
services:
  # -------------------------------------------------------------------------
  repo-server:
    image: repo-server
    container_name: repo-server
    volumes:
      - /Users/zhaoxin/working/docker_data/repo:/repo
    ports: ["7777:7777"]
    networks:
      - cloudera_cluster
  # -------------------------------------------------------------------------
  mysql:
    image: mysql
    volumes:
      - /Users/zhaoxin/working/docker_data/mysql/cloudera:/home/mysql
    ports: ["3306:3306"]
    networks:
      - cloudera_cluster
  # # -------------------------------------------------------------------------
  # manager:
  #   build: ./node
  #   container_name: manager
  #   hostname: "manager"
  #   volumes:
  #     - /Users/zhaoxin/working/docker_data/cloudera:/data
  #   # command: tail -f /dev/null
  #   #environment:
  #   networks:
  #     - cloudera_cluster
  #   ports: ["8080:80", "7180:7180", "7182:7182", "7184:7184", "7185:7185"]
  #   expose: ["22", "3306", "4433", "4434", "7180", "7182", "7184", "7185", "7190", "7191", "8091", "8084", "9000", "9001", "9994", "9995", "9996", "9997", "10101", "8086", "50010", "50075", "50020","8040","3888","60020","53748","13562","2181"]
  #   privileged: true
  #   depends_on:
  #    - mysql
  # # -------------------------------------------------------------------------
  # namenode1:
  #   build: ./node
  #   container_name: namenode1
  #   hostname: "namenode1"
  #   volumes:
  #     - /Users/zhaoxin/working/docker_data/cloudera:/data
  #   # command: tail -f /dev/null
  #   #environment:
  #   networks:
  #     - cloudera_cluster
  #   expose: ["22", "3306", "4433", "4434", "7180", "7182", "7184", "7185", "7190", "7191", "8091", "8084", "9000", "9001", "9994", "9995", "9996", "9997", "10101", "8086", "50010", "50075", "50020","8040","3888","60020","53748","13562","2181"]
  #   privileged: true
  #   depends_on:
  #    - manager
  # # -------------------------------------------------------------------------
  # datanode1:
  #   build: ./node
  #   container_name: datanode1
  #   hostname: "datanode1"
  #   volumes:
  #     - /Users/zhaoxin/working/docker_data/cloudera:/data
  #   # command: tail -f /dev/null
  #   #environment:
  #   networks:
  #     - cloudera_cluster
  #   expose: ["22", "3306", "4433", "4434", "7180", "7182", "7184", "7185", "7190", "7191", "8091", "8084", "9000", "9001", "9994", "9995", "9996", "9997", "10101", "8086", "50010", "50075", "50020","8040","3888","60020","53748","13562","2181"]
  #   privileged: true
  #   depends_on:
  #    - manager
networks:
  cloudera_cluster:
    driver: bridge